name: tox

on:
  create:
    tags:
      - "**"
  push:
    branches:  # any integration branch but not tag
      - "main"
  pull_request:
  schedule:
    - cron: 1 0 * * *  # Run daily at 0:01 UTC

jobs:
  build:
    name: ${{ matrix.tox_env }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - tox_env: lint
            python-version: '3.10'
          # - tox_env: py37-ansible_2
          #   python-version: '3.7'
          - tox_env: py37-ansible_4
            python-version: '3.7'
          - tox_env: py38-ansible_5
            python-version: '3.8'
          - tox_env: py39-ansible_6
            python-version: '3.9'
          - tox_env: py310-ansible_7
            python-version: '3.10'

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Update packages index
        run: |
          sudo apt-get update

      - name: Install a default Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
            python -m pip install -U pip
            pip install tox

      - name: Run tox -e ${{ matrix.tox_env }}
        run: |
          echo "${{ matrix.PREFIX }} tox -e ${{ matrix.tox_env }}"
          tox -e ${{ matrix.tox_env }} 2> debug.log
          # grep -v -i exception debug.log >/dev/null

      - name: Get build container
        id: adocbuild
        uses: tonynv/asciidoctor-action@master
        with:
          program: |
            cd .caradoc/*
            asciidoctor '**/*.adoc' -r asciidoctor-kroki

      - name: Upload logs
        uses: actions/upload-artifact@v3
        with:
          name: logs-upload-${{ matrix.tox_env }}-${{ github.run_id }}
          path: |
            .caradoc
            debug.log
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .caradoc

